# Auto-generated by ryx ORM — 2026-06-04 22:44:07
# Do not edit manually unless you know what you are doing.

from ryx.migrations.autodetect import (
    CreateTable, AddField, AlterField, CreateIndex, RunSQL,
)
from ryx.migrations.state import ColumnState
from app.data.models import AICache, EditorSession, FileHistory, PluginInfo, Project, UserSettings, UserSnippet


class Migration:
    """Migration 0001_ember_create_projects.py

    Operations:
        Create table 'projects'
        Create table 'file_historys'
        Create table 'editor_sessions'
        Create table 'user_snippets'
        Create table 'ai_caches'
        Create table 'user_settingses'
        Create table 'plugin_infos'
    """

    dependencies = []

    operations = [
    CreateTable(
        table='projects',
        columns=[
            ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
            ColumnState(name='name', db_type='VARCHAR(255)', nullable=False),
            ColumnState(name='path', db_type='VARCHAR(1024)', nullable=False, unique=True),
            ColumnState(name='template', db_type='VARCHAR(50)', nullable=False, default='Empty'),
            ColumnState(name='opened_at', db_type='TIMESTAMP', nullable=False),
            ColumnState(name='is_active', db_type='BOOLEAN', nullable=False, default=True),
        ],
        model=Project,
    ),
    CreateTable(
        table='file_historys',
        columns=[
            ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
            ColumnState(name='path', db_type='VARCHAR(1024)', nullable=False),
            ColumnState(name='display_name', db_type='VARCHAR(255)', nullable=False),
            ColumnState(name='language', db_type='VARCHAR(20)', nullable=False, default='text'),
            ColumnState(name='opened_at', db_type='TIMESTAMP', nullable=False),
            ColumnState(name='project_id', db_type='INTEGER'),
        ],
        model=FileHistory,
    ),
    CreateTable(
        table='editor_sessions',
        columns=[
            ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
            ColumnState(name='project_id', db_type='INTEGER'),
            ColumnState(name='open_files', db_type='JSONB'),
            ColumnState(name='active_file', db_type='VARCHAR(1024)'),
            ColumnState(name='cursor_positions', db_type='JSONB'),
            ColumnState(name='saved_at', db_type='TIMESTAMP', nullable=False),
        ],
        model=EditorSession,
    ),
    CreateTable(
        table='user_snippets',
        columns=[
            ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
            ColumnState(name='name', db_type='VARCHAR(100)', nullable=False),
            ColumnState(name='prefix', db_type='VARCHAR(50)', nullable=False),
            ColumnState(name='body', db_type='TEXT', nullable=False),
            ColumnState(name='language', db_type='VARCHAR(20)', nullable=False, default='python'),
            ColumnState(name='scope', db_type='VARCHAR(50)'),
        ],
        model=UserSnippet,
    ),
    CreateTable(
        table='ai_caches',
        columns=[
            ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
            ColumnState(name='prompt_hash', db_type='VARCHAR(64)', nullable=False, unique=True),
            ColumnState(name='response', db_type='TEXT', nullable=False),
            ColumnState(name='provider', db_type='VARCHAR(50)', nullable=False),
            ColumnState(name='model', db_type='VARCHAR(100)', nullable=False),
            ColumnState(name='created_at', db_type='TIMESTAMP', nullable=False),
            ColumnState(name='hit_count', db_type='INTEGER', nullable=False, default=1),
        ],
        model=AICache,
    ),
    CreateTable(
        table='user_settingses',
        columns=[
            ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
            ColumnState(name='key', db_type='VARCHAR(255)', nullable=False, unique=True),
            ColumnState(name='value', db_type='JSONB', nullable=False),
            ColumnState(name='updated_at', db_type='TIMESTAMP', nullable=False),
        ],
        model=UserSettings,
    ),
    CreateTable(
        table='plugin_infos',
        columns=[
            ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
            ColumnState(name='name', db_type='VARCHAR(100)', nullable=False, unique=True),
            ColumnState(name='version', db_type='VARCHAR(20)', nullable=False),
            ColumnState(name='author', db_type='VARCHAR(100)', nullable=False),
            ColumnState(name='description', db_type='TEXT'),
            ColumnState(name='manifest', db_type='JSONB', nullable=False),
            ColumnState(name='enabled', db_type='BOOLEAN', nullable=False, default=True),
            ColumnState(name='installed_at', db_type='TIMESTAMP', nullable=False),
        ],
        model=PluginInfo,
    ),
    ]
