# Auto-generated by ryx ORM — 2026-06-05 10:35:25
# Do not edit manually unless you know what you are doing.

from ryx.migrations.autodetect import (
    CreateTable, AddField, AlterField, CreateIndex, RunSQL,
)
from ryx.migrations.state import ColumnState
from app.data.models import Project


class Migration:
    """Migration 0002_ember_add_color_to_projects.py

    Operations:
        Add field 'color' to 'projects'
        Add field 'avatar' to 'projects'
    """

    dependencies = ["0001_ember_create_projects"]

    operations = [
    AddField(
        table='projects',
        column=ColumnState(name='color', db_type='VARCHAR(24)'),
        model=Project,
    ),
    AddField(
        table='projects',
        column=ColumnState(name='avatar', db_type='VARCHAR(8)'),
        model=Project,
    ),
    ]
