# Auto-generated by ryx ORM — 2026-06-05 10:45:44
# Do not edit manually unless you know what you are doing.

from ryx.migrations.autodetect import (
    CreateTable, AddField, AlterField, CreateIndex, RunSQL,
)
from ryx.migrations.state import ColumnState
from app.data.models import EditorSession


class Migration:
    """Migration 0003_ember_add_workspace_path_to_editor_sessions.py

    Operations:
        Add field 'workspace_path' to 'editor_sessions'
    """

    dependencies = ["0002_ember_add_color_to_projects"]

    operations = [
    AddField(
        table='editor_sessions',
        column=ColumnState(name='workspace_path', db_type='VARCHAR(1024)'),
        model=EditorSession,
    ),
    ]
