# Auto-generated by ryx ORM — 2026-06-06
# Do not edit manually unless you know what you are doing.

from ryx.migrations.autodetect import (
    CreateTable, AddField, AlterField, CreateIndex, RunSQL,
)
from ryx.migrations.state import ColumnState
from app.data.models import PluginInfo


class Migration:
    """Migration 0004_ember_add_plugin_install_audit.py

    Operations:
        Add field 'installed_from' to 'plugin_infos'
        Add field 'manifest_hash' to 'plugin_infos'
        Add field 'trusted' to 'plugin_infos'
    """

    dependencies = ["0003_ember_add_workspace_path_to_editor_sessions"]

    operations = [
        AddField(
            table='plugin_infos',
            column=ColumnState(name='installed_from', db_type='VARCHAR(1024)'),
            model=PluginInfo,
        ),
        AddField(
            table='plugin_infos',
            column=ColumnState(name='manifest_hash', db_type='VARCHAR(64)'),
            model=PluginInfo,
        ),
        AddField(
            table='plugin_infos',
            column=ColumnState(name='trusted', db_type='BOOLEAN', nullable=False, default=False),
            model=PluginInfo,
        ),
    ]
