# Auto-generated by ryx ORM — 2026-06-06
# Do not edit manually unless you know what you are doing.

from ryx.migrations.autodetect import (
    CreateTable, AddField, AlterField, CreateIndex, RunSQL,
)
from ryx.migrations.state import ColumnState
from app.data.models import ToolInstallAudit


class Migration:
    """Migration 0005_ember_create_tool_install_audits.py

    Operations:
        Create table 'tool_install_audits'
    """

    dependencies = ["0004_ember_add_plugin_install_audit"]

    operations = [
        CreateTable(
            table='tool_install_audits',
            columns=[
                ColumnState(name='id', db_type='INTEGER', nullable=False, primary_key=True, unique=True),
                ColumnState(name='provider_id', db_type='VARCHAR(160)', nullable=False),
                ColumnState(name='plugin_name', db_type='VARCHAR(160)'),
                ColumnState(name='command', db_type='TEXT', nullable=False),
                ColumnState(name='status', db_type='VARCHAR(24)', nullable=False),
                ColumnState(name='message', db_type='TEXT'),
                ColumnState(name='stdout', db_type='TEXT'),
                ColumnState(name='stderr', db_type='TEXT'),
                ColumnState(name='created_at', db_type='TIMESTAMP', nullable=False),
            ],
            model=ToolInstallAudit,
        ),
    ]
